### ISSUE TITLE
Terraform crashes while kubernetes cluster is updating

### ISSUE THREAD

**Issue by MoritzKn** [terraform-providers/terraform-provider-digitalocean#272]
### Terraform Version

```
Terraform v0.12.5
+ provider.aws v2.19.0
+ provider.digitalocean v1.5.0
+ provider.kubernetes v1.8.1
```

### Affected Resource(s)

- `digitalocean_kubernetes_cluster` (i think)

### Terraform Configuration Files

```
resource "digitalocean_kubernetes_cluster" "cluster" {
  name    = "some-cluster"
  region  = "fra1"
  version = "1.13.7-do.f.0"

  node_pool {
    name       = "woker-pool"
    size       = "s-2vcpu-4gb"
    node_count = 1
  }
}
```

### Panic Output

Using terraform `0.12.3`:
https://gist.github.com/MoritzKn/1020c309bff80941e6f0fe58be2c503d

Using terraform `0.12.5` (latest):
https://gist.github.com/MoritzKn/ffaf5e646aa8d007f2c5461981701661

### Expected Behavior

No crash

### Actual Behavior

Terraform crashes

### Steps to Reproduce

I'm not sure if it is reproducible but I did the following steps leading up to the crash:

1. I clicked the update Kubernetes button in the DO web interface
2. I changed the version in the terraform config to the one displayed in the web interface
3. I ran `terraform plan` -> crash
4. I updated terraform to the lastest version (from `0.12.3` to `0.12.5`)
5. I ran `terraform plan` again -> still crashing
6. I waited a few minutes and it stated working again

**Comment by andrewsomething** [comment]
Pulling out the actual panic:

```
  panic: runtime error: invalid memory address or nil pointer dereference
  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19ac5e0]
  goroutine 50 [running]:
  github.com/terraform-providers/terraform-provider-digitalocean/digitalocean.resourceDigitalOceanKubernetesClusterRead(0xc0001f0cb0, 0x1af3d60, 0xc000541a70, 0xc0001f0cb0, 0x0)
  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-digitalocean/digitalocean/resource_digitalocean_kubernetes_cluster.go:181 +0xe0
  github.com/terraform-providers/terraform-provider-digitalocean/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000185b00, 0xc0000c0dc0, 0x1af3d60, 0xc000541a70, 0xc000152a20, 0xc0000c0dc0, 0x0)
  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-digitalocean/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:447 +0x11c
  github.com/terraform-providers/terraform-provider-digitalocean/vendor/github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000c5a0, 0x1df3600, 0xc0003c54a0, 0xc00047a580, 0xc00000c5a0, 0xc0003c5410, 0x1aee0c0)
  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-digitalocean/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:496 +0x30b
  github.com/terraform-providers/terraform-provider-digitalocean/vendor/github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadResource_Handler(0x1bfdc80, 0xc00000c5a0, 0x1df3600, 0xc0003c54a0, 0xc0000c0b90, 0x0, 0x0, 0x0, 0xc0002ce000, 0x308b)
  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-digitalocean/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:2983 +0x23e
  github.com/terraform-providers/terraform-provider-digitalocean/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000b2a80, 0x1df9d20, 0xc0000b3b00, 0xc00046db00, 0xc000098900, 0x269fef0, 0x0, 0x0, 0x0)
  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-digitalocean/vendor/google.golang.org/grpc/server.go:966 +0x4a2
  github.com/terraform-providers/terraform-provider-digitalocean/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0000b2a80, 0x1df9d20, 0xc0000b3b00, 0xc00046db00, 0x0)
  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-digitalocean/vendor/google.golang.org/grpc/server.go:1245 +0xd61
  github.com/terraform-providers/terraform-provider-digitalocean/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000400660, 0xc0000b2a80, 0x1df9d20, 0xc0000b3b00, 0xc00046db00)
  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-digitalocean/vendor/google.golang.org/grpc/server.go:685 +0x9f
  created by github.com/terraform-providers/terraform-provider-digitalocean/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-digitalocean/vendor/google.golang.org/grpc/server.go:683 +0xa1
```

It points to: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/digitalocean/resource_digitalocean_kubernetes_cluster.go#L181

So it seems like ` client.Kubernetes.Get` is erroring without returning a response.
